// @ts-check
/**
 * 運動項目：維基頁名（「<英文> at the <屆次>」）→ 統一代碼與繁體中文名。
 * 同一運動的不同寫法（例：Synchronized swimming / Artistic swimming）歸到同一個代碼。
 * 藝術競賽與 1900 年巴黎的特殊表演項目（放風箏、賽鴿等）不列入，國際奧會獎牌榜也不計。
 */

/** @type {Record<string, [id: string, zh: string]>} */
export const SPORT_BY_EN = {
  Athletics: ['athletics', '田徑'],
  Swimming: ['swimming', '游泳'],
  Diving: ['diving', '跳水'],
  'Water polo': ['water-polo', '水球'],
  'Synchronized swimming': ['artistic-swimming', '藝術游泳（韻律泳）'],
  'Synchronised swimming': ['artistic-swimming', '藝術游泳（韻律泳）'],
  'Artistic swimming': ['artistic-swimming', '藝術游泳（韻律泳）'],
  'Marathon swimming': ['marathon-swimming', '公開水域游泳'],
  Cycling: ['cycling', '自行車'],
  Wrestling: ['wrestling', '角力'],
  Football: ['football', '足球'],
  'Association football': ['football', '足球'],
  Shooting: ['shooting', '射擊'],
  Weightlifting: ['weightlifting', '舉重'],
  Boxing: ['boxing', '拳擊'],
  Gymnastics: ['gymnastics', '體操'],
  Fencing: ['fencing', '擊劍'],
  Basketball: ['basketball', '籃球'],
  '3x3 basketball': ['basketball-3x3', '三對三籃球'],
  'Field hockey': ['hockey', '曲棍球'],
  Sailing: ['sailing', '帆船'],
  Rowing: ['rowing', '划船'],
  Equestrian: ['equestrian', '馬術'],
  'Equestrian events': ['equestrian', '馬術'],
  Tennis: ['tennis', '網球'],
  Volleyball: ['volleyball', '排球'],
  'Beach volleyball': ['beach-volleyball', '沙灘排球'],
  'Modern pentathlon': ['modern-pentathlon', '現代五項'],
  Archery: ['archery', '射箭'],
  Canoeing: ['canoeing', '輕艇'],
  Handball: ['handball', '手球'],
  Badminton: ['badminton', '羽球'],
  'Table tennis': ['table-tennis', '桌球'],
  Judo: ['judo', '柔道'],
  Baseball: ['baseball', '棒球'],
  Softball: ['softball', '壘球'],
  Taekwondo: ['taekwondo', '跆拳道'],
  Golf: ['golf', '高爾夫'],
  Triathlon: ['triathlon', '鐵人三項'],
  Bowling: ['bowling', '保齡球'],
  Karate: ['karate', '空手道'],
  Kabaddi: ['kabaddi', '卡巴迪'],
  'Sepak takraw': ['sepak-takraw', '藤球'],
  Sepaktakraw: ['sepak-takraw', '藤球'],
  'Soft tennis': ['soft-tennis', '軟式網球'],
  Wushu: ['wushu', '武術'],
  'Rugby sevens': ['rugby-sevens', '七人制橄欖球'],
  'Rugby union': ['rugby', '橄欖球'],
  Squash: ['squash', '壁球'],
  Cricket: ['cricket', '板球'],
  Polo: ['polo', '馬球'],
  'Tug of war': ['tug-of-war', '拔河'],
  Lacrosse: ['lacrosse', '袋棍球'],
  'Sport climbing': ['climbing', '運動攀登'],
  'Basque pelota': ['basque-pelota', '巴斯克回力球'],
  'Cue sports': ['cue-sports', '撞球'],
  Skateboarding: ['skateboarding', '滑板'],
  Surfing: ['surfing', '衝浪'],
  Breaking: ['breaking', '霹靂舞'],
  Breakdancing: ['breaking', '霹靂舞'],
  Chess: ['chess', '西洋棋'],
  'Dragon boat': ['dragon-boat', '龍舟'],
  'Roller sports': ['roller-sports', '滑輪運動'],
  'Ju-jitsu': ['jujitsu', '柔術'],
  Jujitsu: ['jujitsu', '柔術'],
  Kurash: ['kurash', '克拉什摔角'],
  Esports: ['esports', '電子競技'],
  ESports: ['esports', '電子競技'],
  'Water motorsports': ['water-motorsports', '摩托艇'],
  Go: ['go', '圍棋'],
  Xiangqi: ['xiangqi', '象棋'],
  Bridge: ['bridge', '橋牌'],
  Bodybuilding: ['bodybuilding', '健美'],
  Dancesport: ['dancesport', '運動舞蹈'],
  Croquet: ['croquet', '槌球'],
  Roque: ['roque', '羅克球'],
  'Jeu de paume': ['jeu-de-paume', '室內網球'],
  Rackets: ['rackets', '壁拍球'],
  'Pencak silat': ['pencak-silat', '班卡西拉'],
  Sambo: ['sambo', '桑搏'],
  Paragliding: ['paragliding', '滑翔傘'],
  'Canoe polo': ['canoe-polo', '輕艇水球'],
  'Jet ski': ['jet-ski', '水上摩托車'],
  Muaythai: ['muaythai', '泰拳'],
  'Mixed martial arts': ['mma', '綜合格鬥'],
  Teqball: ['teqball', '桌式足球'],
  Padel: ['padel', '板式網球'],
  // 冬季
  'Figure skating': ['figure-skating', '花式滑冰'],
  'Ice hockey': ['ice-hockey', '冰上曲棍球'],
  'Cross-country skiing': ['cross-country-skiing', '越野滑雪'],
  'Cross country skiing': ['cross-country-skiing', '越野滑雪'],
  'Nordic combined': ['nordic-combined', '北歐兩項'],
  'Nordic Combined': ['nordic-combined', '北歐兩項'],
  'Ski jumping': ['ski-jumping', '跳台滑雪'],
  'Speed skating': ['speed-skating', '競速滑冰'],
  Bobsleigh: ['bobsleigh', '雪車'],
  'Alpine skiing': ['alpine-skiing', '高山滑雪'],
  Biathlon: ['biathlon', '冬季兩項'],
  Luge: ['luge', '單人雪橇'],
  Curling: ['curling', '冰壺'],
  'Freestyle skiing': ['freestyle-skiing', '自由式滑雪'],
  'Short track speed skating': ['short-track', '短道競速滑冰'],
  'Short-track speed skating': ['short-track', '短道競速滑冰'],
  Skeleton: ['skeleton', '俯式冰橇'],
  Snowboarding: ['snowboarding', '單板滑雪'],
  'Nordic skiing': ['nordic-skiing', '北歐滑雪'],
  'Military patrol': ['military-patrol', '軍事巡邏'],
  'Ski mountaineering': ['ski-mountaineering', '滑雪登山'],
}

/** @type {Record<string, string>} 代碼 → 中文名 */
export const SPORT_ZH = Object.fromEntries(Object.values(SPORT_BY_EN).map(([id, zh]) => [id, zh]))
